### ISSUE TITLE
Show location in popup

### ISSUE THREAD

**Issue by MartinAronsen** [stoo2000/membermap#16]
> When i look on the map, i'm searching for members to talk or meet with. However, not being very confident about their location, i'm always accessing their profile to see what is actually written in their location field.
> 
> I believe displaying the custom location field (they entered when registering) on the map, under the member name in the map marker would help a lot. Even a contact or send message button would help.

Got this on a PM.

**Comment by Admonstrator** [comment]
PN Button would be nicht to have but it's not necessary because you can visit the profile of a member with a simple click. In our forum we don't use the custom location field and everyone is just adding their location by visiting the map and creating a marker - so there is no need for us to have the custom field shown on the map. (But this might be different for other communities)

So if this feature will be done it would be nice if you can configure if the field should be shown or not.

**Comment by MartinAronsen** [comment]
What I’m thinking is using the same field as chosen in the settings to sync members location. If that’s enabled, use that.
If not, use the location the member chose when searching in Member Map. Those who use HTML$ Geocode will still show as blank.

**Comment by MartinAronsen** [comment]
37708f32da098ea09254989a72f302cd86c34c73
