### ISSUE TITLE
Markers visible to guest

### ISSUE THREAD

**Issue by szastan** [stoo2000/membermap#35]
Hi, I just installed your extension (ips 4.1.17.1), and I found out that regardless of restricting guests to see any markers, I can see them while being logged out.

**Comment by MartinAronsen** [comment]
What have you done in order to restrict guest access? Setting the view permission on the marker group will currently not remove them from the map for guests. 

The proper way is going to ACP > Applications, click on the Member Map row to expand it, then set the permission for each of the two modules.

**Comment by szastan** [comment]
That was the case, I was changing permissions in ACP / Users / Groups and /Content / Member map. Thanks for clarifying that.

**Comment by MartinAronsen** [comment]
Fixed the fact that the marker group permission wasn't honored by the map in 3.1.7.
