### ISSUE TITLE
Question: Import Map Data to Member Map

### ISSUE THREAD

**Issue by AndiKnight** [stoo2000/membermap#37]
Hi, 
is it possible to import data from zeemaps.com/csv?
Would be great if so, because our old map has thousands of markers and it would be uncool to lose them.
Export to csv is possible from zeemaps.
![Image of Export](https://i.shrt.li/root_Januar21_1485004163_CWSondors_Storm_Owners_locations_-_Google_Chrome.jpg)

(Our old map: https://www.zeemaps.com/map?group=1330458&location=North%2BAmerica)

**Comment by MartinAronsen** [comment]
The export tool provided in Zeemaps is not made to be used with other platforms, as they do not include latitude and longitude in the file, unless you're subscribed to their enterprise plan.
I think it's only made as a way for you to keep a local backup, or mass-update markers locally.

That being said, if you had the enterprise plan, and Member Map had a way to import a CSV file, the imported markers would not be attached to any members of your community. You could then end up with duplicate markers when your members are adding themselves to the map, either manually or through the profile synchronization feature.

https://www.zeemaps.com/pricing

**Comment by Admonstrator** [comment]
Sorry to interrupt your conversation but in fact it could be possible with a couple of working hours. Please correct me if I am wrong. I did something liek this before because I had to import markers from an excel file without geo coordinates.

The following might help you:
- Create a testing installation of IPS and copy your database
- Rewrite the CSV file to map your users (maybe by matching usernames?)
- Be sure that you have a custom field "location" in your test installation of IPS, make sure that the provided location from Zeemap fits in the "location" field
- Import the CSV file as a new user database (so the location field will be filled correctly)
- Testing!
- Export the whole user database and import it to your live environment
- Use the profile sync function of Membermap to restore markers

I'm sorry that there is no detailed way how to do that - I just did it by myself in around 2 or 3 days.
It was a bit tricky but possible. I'm not sure if this way would be working for you because I do not know the CSV file from Zeemaps.

Sorry for my bad english, it is not my native language.

**Comment by Admonstrator** [comment]
@MartinAronsen Yup, should be enough.
 But I am pretty sure that it will be not easy to match every marker ... but it is worth a try.

**Comment by MartinAronsen** [comment]
If you open it as a spreadsheet first you can add a new column which concatenates the three location fields into one.

**Comment by Admonstrator** [comment]
But still a hard task with some kind of preparation before.
You have to be sure that the usernames are identically in both systems (map & IPS)

If you are able to work with SQL this will be much faster ... unfortunately I am not an SQL expert so I did the most things by using Notepad++ and Excel. 😄 

@AndiKnight If you want to I can try to support you with this task. No promise that everything will be working afterwards - but with a bit luck it should be no problem.

**Comment by AndiKnight** [comment]
Hi @Admonstrator 
thanks for the offer, I appreciate your work. The Problem is: I'm hundert percent sure, 99% of the Names in the Map are not matching the Forum Usernames. So, I will just tell them to mark them again 👍 ,

@MartinAronsen Thanks for looking into this, request.

Have a nice day,
Andi
